// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdminGetShortLinkByID(ctx context.Context, id uuid.UUID) (ShortLink, error)
	AdminGetShortLinksByUserID(ctx context.Context, arg AdminGetShortLinksByUserIDParams) ([]ShortLink, error)
	AdminListShortLinks(ctx context.Context, arg AdminListShortLinksParams) ([]ShortLink, error)
	AdminToggleShortLinkStatus(ctx context.Context, id uuid.UUID) error
	CheckShortCodeExists(ctx context.Context, shortCode string) (bool, error)
	CountActiveLinks(ctx context.Context) (int64, error)
	CountInactiveLinks(ctx context.Context) (int64, error)
	CountLinks(ctx context.Context) (int64, error)
	CountUserShortLinks(ctx context.Context, arg CountUserShortLinksParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Records a click event when someone accesses a short link with custom UUID v7
	CreateLinkStat(ctx context.Context, arg CreateLinkStatParams) (LinkStat, error)
	CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateShortLink(ctx context.Context, id uuid.UUID) (ShortLink, error)
	DecrementClickLimit(ctx context.Context, id uuid.UUID) (ShortLink, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserShortLink(ctx context.Context, id uuid.UUID) error
	GetActiveShortLinkByCode(ctx context.Context, shortCode string) (ShortLink, error)
	// Returns all stats for a specific link owned by the user
	GetLinkStats(ctx context.Context, arg GetLinkStatsParams) ([]LinkStat, error)
	// Returns all stats for a specific link within a date range
	GetLinkStatsByDateRange(ctx context.Context, arg GetLinkStatsByDateRangeParams) ([]LinkStat, error)
	// Returns the total count of stats entries for a specific link
	GetLinkStatsCount(ctx context.Context, arg GetLinkStatsCountParams) (int64, error)
	// Returns stats grouped by country for a specific link
	GetLinkStatsGroupedByCountry(ctx context.Context, arg GetLinkStatsGroupedByCountryParams) ([]GetLinkStatsGroupedByCountryRow, error)
	// Returns stats grouped by date for a specific link
	GetLinkStatsGroupedByDate(ctx context.Context, arg GetLinkStatsGroupedByDateParams) ([]GetLinkStatsGroupedByDateRow, error)
	GetShortLink(ctx context.Context, id uuid.UUID) (ShortLink, error)
	GetShortLinkByCode(ctx context.Context, shortCode string) (ShortLink, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListShortLinks(ctx context.Context, arg ListShortLinksParams) ([]ShortLink, error)
	ListUserShortLinks(ctx context.Context, arg ListUserShortLinksParams) ([]ShortLink, error)
	ListUserShortLinksWithCountClick(ctx context.Context, arg ListUserShortLinksWithCountClickParams) ([]ListUserShortLinksWithCountClickRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	ToggleShortLinkStatus(ctx context.Context, id uuid.UUID) (ShortLink, error)
	UpdateShortLink(ctx context.Context, arg UpdateShortLinkParams) (ShortLink, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
