// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminGetShortLinkByID(ctx context.Context, id uuid.UUID) (ShortLink, error)
	AdminGetShortLinksByUserID(ctx context.Context, arg AdminGetShortLinksByUserIDParams) ([]ShortLink, error)
	AdminListShortLinks(ctx context.Context, arg AdminListShortLinksParams) ([]ShortLink, error)
	AdminToggleShortLinkStatus(ctx context.Context, id uuid.UUID) error
	CheckShortCodeExists(ctx context.Context, shortCode string) (bool, error)
	CountActiveLinks(ctx context.Context) (int64, error)
	CountInactiveLinks(ctx context.Context) (int64, error)
	CountLinks(ctx context.Context) (int64, error)
	CountUserShortLinks(ctx context.Context, arg CountUserShortLinksParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateLinkStat(ctx context.Context, arg CreateLinkStatParams) error
	CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateShortLink(ctx context.Context, id uuid.UUID) (ShortLink, error)
	DecrementClickLimit(ctx context.Context, id uuid.UUID) (ShortLink, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserShortLink(ctx context.Context, id uuid.UUID) error
	GetActiveShortLinkByCode(ctx context.Context, shortCode string) (ShortLink, error)
	GetLinkClickStatsByDateRange(ctx context.Context, arg GetLinkClickStatsByDateRangeParams) ([]GetLinkClickStatsByDateRangeRow, error)
	GetShortLink(ctx context.Context, id uuid.UUID) (ShortLink, error)
	GetShortLinkByCode(ctx context.Context, shortCode string) (ShortLink, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Mengambil data time-series jumlah klik per hari untuk pengguna tertentu dalam rentang waktu.
	// Berguna untuk membuat grafik tren klik dari waktu ke waktu.
	GetUserClickTimeline(ctx context.Context, arg GetUserClickTimelineParams) ([]GetUserClickTimelineRow, error)
	// Mengelompokkan jumlah klik berdasarkan negara untuk semua link milik pengguna.
	// Berguna untuk membuat diagram statistik geografis.
	GetUserClicksByCountry(ctx context.Context, userID uuid.UUID) ([]GetUserClicksByCountryRow, error)
	// Mengelompokkan jumlah klik berdasarkan sumber trafik (referrer) untuk semua link milik pengguna.
	// Dibatasi dengan LIMIT untuk mengambil N sumber teratas.
	GetUserClicksByReferrer(ctx context.Context, arg GetUserClicksByReferrerParams) ([]GetUserClicksByReferrerRow, error)
	// Mengambil statistik ringkas untuk dashboard pengguna: jumlah total link dan jumlah total klik.
	GetUserDashboardStats(ctx context.Context, userID pgtype.UUID) (GetUserDashboardStatsRow, error)
	GetUserLinkStats(ctx context.Context, userID uuid.UUID) (GetUserLinkStatsRow, error)
	// Mengambil daftar link milik pengguna beserta jumlah klik untuk setiap link, dengan paginasi.
	// Menggunakan LEFT JOIN untuk memastikan link yang belum pernah diklik (0 klik) tetap muncul.
	GetUserLinksWithStats(ctx context.Context, arg GetUserLinksWithStatsParams) ([]GetUserLinksWithStatsRow, error)
	ListShortLinks(ctx context.Context, arg ListShortLinksParams) ([]ShortLink, error)
	ListUserShortLinks(ctx context.Context, arg ListUserShortLinksParams) ([]ShortLink, error)
	ListUserShortLinksWithCountClick(ctx context.Context, arg ListUserShortLinksWithCountClickParams) ([]ListUserShortLinksWithCountClickRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	ToggleShortLinkStatus(ctx context.Context, id uuid.UUID) (ShortLink, error)
	UpdateShortLink(ctx context.Context, arg UpdateShortLinkParams) (ShortLink, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
