name: Deploy on Master

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and start containers
        run: |
          docker-compose down
          docker-compose up --build -d